name = "example"
bin = "bin/example"
vcs = "git"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = false
with_yarn = true
with_docker = false
with_grifts = false
as_web = false
as_api = true
